name: 'codespy'
description: 'Fast, offline code security scanner. Zero dependencies. Finds secrets, injection vulnerabilities, misconfigurations, and code quality issues across 13+ languages.'
author: 'wisent-ai'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  path:
    description: 'Path to scan (relative to workspace root)'
    required: false
    default: '.'
  severity-threshold:
    description: 'Minimum severity to report: info, low, medium, high, critical'
    required: false
    default: 'high'
  output-format:
    description: 'Output format: terminal, json, sarif, markdown'
    required: false
    default: 'markdown'
  scan-changed-only:
    description: 'Only scan files changed in the current pull request (ignored on push events)'
    required: false
    default: 'true'
  post-comment:
    description: 'Post a PR comment with findings summary (requires pull_request event)'
    required: false
    default: 'true'
  fail-on-findings:
    description: 'Fail the action if findings at or above the severity threshold are found. Set to "false" to never fail.'
    required: false
    default: 'true'
  sarif-upload:
    description: 'Upload SARIF results to GitHub Code Scanning / Security tab'
    required: false
    default: 'false'
  show-fixes:
    description: 'Include fix suggestions in output'
    required: false
    default: 'true'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

outputs:
  total-findings:
    description: 'Total number of findings'
    value: ${{ steps.scan.outputs.total_findings }}
  critical-count:
    description: 'Number of critical findings'
    value: ${{ steps.scan.outputs.critical_count }}
  high-count:
    description: 'Number of high findings'
    value: ${{ steps.scan.outputs.high_count }}
  medium-count:
    description: 'Number of medium findings'
    value: ${{ steps.scan.outputs.medium_count }}
  low-count:
    description: 'Number of low findings'
    value: ${{ steps.scan.outputs.low_count }}
  security-score:
    description: 'Security score (0-100)'
    value: ${{ steps.scan.outputs.security_score }}
  security-grade:
    description: 'Security grade (A+ to F)'
    value: ${{ steps.scan.outputs.security_grade }}
  sarif-file:
    description: 'Path to SARIF output file (if generated)'
    value: ${{ steps.scan.outputs.sarif_file }}
  report-file:
    description: 'Path to the scan report file'
    value: ${{ steps.scan.outputs.report_file }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Run codespy scan
      id: scan
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_SEVERITY_THRESHOLD: ${{ inputs.severity-threshold }}
        INPUT_OUTPUT_FORMAT: ${{ inputs.output-format }}
        INPUT_SCAN_CHANGED_ONLY: ${{ inputs.scan-changed-only }}
        INPUT_POST_COMMENT: ${{ inputs.post-comment }}
        INPUT_FAIL_ON_FINDINGS: ${{ inputs.fail-on-findings }}
        INPUT_SARIF_UPLOAD: ${{ inputs.sarif-upload }}
        INPUT_SHOW_FIXES: ${{ inputs.show-fixes }}
        CODESPY_SCRIPT: ${{ github.action_path }}/codespy.py
        CODESPY_ENTRYPOINT: ${{ github.action_path }}/entrypoint.sh
      run: |
        chmod +x "$CODESPY_ENTRYPOINT"
        bash "$CODESPY_ENTRYPOINT"

    - name: Upload SARIF to GitHub Code Scanning
      if: inputs.sarif-upload == 'true' && always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif_file || 'codespy-results.sarif' }}
      continue-on-error: true
