//! Markdown report for review threads and job summaries.

use crate::identity::{INFORMATION_URI, VERSION};
use crate::model::{ScanResult, Severity};

use super::{by_file, summary_order, thousands, ScoringReport};

/// One mark per severity; every severity the model defines has one.
fn severity_mark(severity: Severity) -> &'static str {
    match severity {
        Severity::Critical => "🔴",
        Severity::High => "🟠",
        Severity::Medium => "🟡",
        Severity::Low => "🔵",
        Severity::Info => "⚪",
    }
}

/// The scan as a Markdown report; with `show_fix` each finding's suggestion.
pub fn format_markdown(result: &ScanResult, scoring: &ScoringReport<'_>, show_fix: bool) -> String {
    let mut lines = vec![
        "# codespy Security Report".to_owned(),
        String::new(),
        format!("**Path:** `{}`  ", result.path),
        format!("**Files scanned:** {}  ", result.files_scanned),
        format!("**Lines scanned:** {}  ", thousands(result.lines_scanned)),
        format!("**Scan time:** {:.0}ms  ", result.scan_duration_ms),
        String::new(),
        format!("## {}", scoring.summary()),
        String::new(),
    ];
    if scoring.policy.is_some() {
        lines.extend([
            "Scoring policy:".to_owned(),
            "```json".to_owned(),
            scoring.policy_json(),
            "```".to_owned(),
            String::new(),
        ]);
    }
    lines.extend([
        "## Summary".to_owned(),
        String::new(),
        "| Severity | Count |".to_owned(),
        "|----------|-------|".to_owned(),
    ]);
    let counts = result.severity_counts();
    for severity in summary_order() {
        let count = counts[severity.as_str()];
        if count > 0 {
            let name = severity.as_str().to_uppercase();
            lines.push(format!("| {} {name} | {count} |", severity_mark(severity)));
        }
    }
    lines.push(String::new());

    if result.findings.is_empty() {
        lines.push("**No issues found!** ✅".to_owned());
        return lines.join("\n");
    }

    lines.push("## Findings".to_owned());
    lines.push(String::new());
    for (file_path, findings) in by_file(result) {
        lines.push(format!("### `{file_path}`"));
        lines.push(String::new());
        for finding in findings {
            lines.push(format!(
                "- {} **[{}] {}** (L{})",
                severity_mark(finding.severity),
                finding.rule_id,
                finding.title,
                finding.line_number,
            ));
            lines.push(format!("  - {}", finding.description));
            if show_fix && !finding.suggestion.is_empty() {
                lines.push(format!("  - 💡 **Fix:** {}", finding.suggestion));
            }
        }
        lines.push(String::new());
    }
    lines.push("---".to_owned());
    lines.push(format!(
        "*Generated by [codespy]({INFORMATION_URI}) v{VERSION}*"
    ));
    lines.join("\n")
}
