"""Markdown report for review threads and job summaries."""

from collections import defaultdict

from ..configuration import __version__
from ..models import ScanResult
from .scoring import compute_score, score_to_grade


def format_markdown(result: ScanResult, show_fix: bool = False) -> str:
    """Format scan results as Markdown."""
    lines = []
    lines.append(f"# codespy Security Report")
    lines.append(f"")
    lines.append(f"**Path:** `{result.path}`  ")
    lines.append(f"**Files scanned:** {result.files_scanned}  ")
    lines.append(f"**Lines scanned:** {result.lines_scanned:,}  ")
    lines.append(f"**Scan time:** {result.scan_duration_ms:.0f}ms  ")
    lines.append(f"")

    score = compute_score(result)
    grade = score_to_grade(score)
    lines.append(f"## Security Score: {score}/100 (Grade: {grade})")
    lines.append(f"")

    # Severity summary
    lines.append(f"## Summary")
    lines.append(f"")
    lines.append(f"| Severity | Count |")
    lines.append(f"|----------|-------|")
    sc = result.severity_counts
    for sev in ["critical", "high", "medium", "low", "info"]:
        count = sc.get(sev, 0)
        if count > 0:
            emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}
            lines.append(f"| {emoji[sev]} {sev.upper()} | {count} |")
    lines.append(f"")

    if not result.findings:
        lines.append(f"**No issues found!** ✅")
        return "\n".join(lines)

    # Findings
    lines.append(f"## Findings")
    lines.append(f"")

    findings_by_file = defaultdict(list)
    for f in result.findings:
        findings_by_file[f.file_path].append(f)

    for file_path, file_findings in sorted(findings_by_file.items()):
        lines.append(f"### `{file_path}`")
        lines.append(f"")
        for f in file_findings:
            emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}
            lines.append(f"- {emoji.get(f.severity.value, '')} **[{f.rule_id}] {f.title}** (L{f.line_number})")
            lines.append(f"  - {f.description}")
            if show_fix and f.suggestion:
                lines.append(f"  - 💡 **Fix:** {f.suggestion}")
        lines.append(f"")

    lines.append(f"---")
    lines.append(f"*Generated by [codespy](https://github.com/wisent-ai/codespy) v{__version__}*")

    return "\n".join(lines)
